### ISSUE TITLE
Overhaul the GraphQL workshop

### ISSUE THREAD

**Issue by anapaulalemos** [nearform/the-graphql-workshop#405]
The GraphQL workshop could be improved.

Currently, it only presents the code with the solutions for the challenges proposed in the slides and the content of the steps does not necessarily have a connection between them.

My suggestion would be to update it so that it follows the same model as [The Fastify workshop](https://github.com/nearform/the-fastify-workshop):
* Create a dedicated folder for development (something like the `src/start-here` folder in the Fastify workshop)
* Make the content incremental, where each module is built on top of the previous one (which is said in the `Workshop architecture` slide but is not necessarily how it is done)
* At each step add documentation links to facilitate a deeper understanding of the subject
* There are some slides where new subjects are brought up (like `variables` and `fragments`) but a introduction about them is missing
* I would also suggest adding steps for testing, caching and subscriptions

**Comment by brainrepo** [comment]
# Mercurius graphql workshop refactoring (Improvement proposal)

@simoneb Here is an improvement proposal for the GraphQL workshop.

## General
Create two folders per step, one with the starting point to implement the feature and the other with the solution.
Per each step, create a slide showing how to test the feature.

Since we introduce the directory structure per step, the example's change may be unnecessary. 

## Steps
### 1 Basic
Instead of getting a simple sum, create a query for getting the pets. This also shows the type definition that is implicit in the workshop.

### 2 Executable schema 
Do we need a specific point for executable schemas? Can we treat it as a "bonus tip of point 1"? If yes, we can move it inside a subfolder of step 1, calling it "bonus features", It will be next to the starting point and the solution folder.
step1 :
starting
solution
bonus features

### 3 loaders
no changes

### 4 n + 1
no changes

### 5 context
Instead of using the current example, filter by the locale of the pet owner or by genre ex. Dog/cat...

### To be added: Migration example

### 6 hooks
migrate the example to the pet version instead of the sum

### 7 Error handling
migrate the example to the pet version (invalid owner or pet. id)

### 8 federation
change the example to the pets version
	service 1: pets, owner
	service 2: veterinary
	service 3: gateway

### 9 variables
This should be moved after step 2, with a simple example of getting a specific pet by id.
	
### 10 Fragment
we can change the example. We can get the address info from the pet's owner and veterinarian. The information can contain a name, surname, and email.

### 11 To be added: Subscription example

**Comment by simoneb** [comment]
I doesn't look like we're going to do this, so closing for now
